spring:
  application:
    name: beat-seeker-backend

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:}
    password: ${GMAIL_APP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d6f68314tr6s73bnbhag-a.oregon-postgres.render.com/beatseeker}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgress}
    password: ${SPRING_DATASOURCE_PASSWORD:kAw2xymPeLH4mOZuV76hsJCR4L9kFkgM}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080



# CORS: allow frontend dev server
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

vapid:
  public:
    key: BDGlranXpFZQs_QO3pNXvrNudlAgliWJFOILQZxXd8_kjGZyRqEJQtJWN6Jymd5PnlFe3ITpTBgRt8v6dLcXIvE
  private:
    key: jGZyRqEJQtJWN6Jymd5PnlFe3ITpTBgRt8v6dLcXIvE
  subject: mailto:admin@example.com
