spring:
  application:
    name: beat-seeker-backend

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:}
    password: ${GMAIL_APP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d6f68314tr6s73bnbhag-a.oregon-postgres.render.com/beatseeker}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgress}
    password: ${SPRING_DATASOURCE_PASSWORD:kAw2xymPeLH4mOZuV76hsJCR4L9kFkgM}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      initialization-fail-timeout: -1
      connection-init-sql: SET statement_timeout = '30s'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080



# CORS: allow frontend dev server
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

vapid:
  public:
    key: BK8nOI89kHqMXjG1Pz5MiOLMc7lX8zjgd-gd3KhfRfr3mD_pt_VgRBFPzPRvmPoDhz06o82fBbBmVLATrotGB0k
  private:
    key: w9dtbWdRCwDU0C3k2MCRkjUzr-mozK2qtFchFU56SYk
  subject: mailto:admin@example.com

kofi:
  verification:
    token: ${KOFI_VERIFICATION_TOKEN:}
